:construction: Header addon done, needs refactor

diff --git a/annotator/annota b/annotator/annota
--- a/annotator/annota
+++ b/annotator/annota
@@ -1,14 +1,15 @@
 #!/usr/bin/env bash
 set -e
-source ./checkfiletype
 
 # annota is meant to be used in conjunction with upnup.
 # although it can be utilized on its on, its functionality is limited
 
+source "$HOME"/.config/upnup/annotator/checkfiletype
+
 printhelp () {
     printf "%s\n" "Usage: block filetype headerfile outputfile"
     printf "%s\n" "Usage: inline filetype headerfile outputfile"
-    printf "%s\n" "Example: block js agpl-3.0 example.js"
+    printf "%s\n" "Example: annota block js agpl-3.0 example.js"
     exit 0
 }
 
@@ -23,7 +24,7 @@ annota () {
     fi
 
     if [[ $blocktype != "block" &&  $blocktype != "inline" ]] ; then
-        echo "error: only 'block' or 'inline' are recognized blocktypes"
+        printf "%s\n" "error: only 'block' or 'inline' are recognized blocktypes"
         exit 1
     fi
 
@@ -45,6 +46,10 @@ annota () {
         cat "$outputfile" >> tmp
         rm "$outputfile"
         mv tmp "$outputfile"
+        exit 0
+    else
+        printf "%s\n" "error: specified filetype is not supported by annota"
+        exit 1
     fi
 }
 
diff --git a/upnup b/upnup
--- a/upnup
+++ b/upnup
@@ -7,6 +7,7 @@ printhelp () {
     printf "%s\n" "Options:"
     printf "%s\n" "  -V, --version              output the version number"
     printf "%s\n" "  -h, --help                 output usage information"
+    printf "%s\n" "  -f, --file <file>          the file to add a header to"
     printf "%s\n" ""
     printf "%s\n" "Commands:"
     printf "%s\n" "  list|l                     List all available licenses"
@@ -21,7 +22,7 @@ main () {
     license_list="$(find "$HOME"/.config/upnup/licenses | sed 1d | awk -F '/' '{ print $7 }' | sort)"
     lcs_list=( agpl-3.0 apache-2.0 bsd-2-clause bsd-3-clause bsl-1.0 cc0-1.0 cc0-3.0 cc0-4.0 epl-2.0 gpl-2.0 gpl-3.0 lgpl-2.1 mit mpl-2.0 unlicense )
     mod_list=( agpl-3.0 bsd-2-clause bsd-3-clause mit )
-
+    header_list=( agpl-3.0 apache-2.0 cc-1.0 cc0-3.0 cc0-4.0 gpl-2.0 gpl-3.0 lgpl-2.1 lgpl-3.0 )
     if [[ $# -lt 1 ]] ; then
         printhelp
     fi
@@ -34,11 +35,39 @@ main () {
         elif [[ "${args[$i]}" == '-y' || "${args[$i]}" == '--year' ]] ; then
             year="${args[$j]}"
 
+        elif [[ "${args[$i]}" == '-f' || "${args[$i]}" == '--file' ]] ; then
+            if [ "${args[$j]}" == '' ] ; then
+                printf "%s\n" "error: missing required argument \`header_file'"
+                exit 1
+            fi
+
+            headerfile="${args[$j]}"
+            if [[ ! "${header_list[*]}" =~ ${headerfile} ]] ; then
+                printf "%s\n" "error: requested headerfile is not supported"
+                exit 1
+            fi
+
+            for (( k = 0; k < $#; k++ )) ; do
+                m=$((k + 1))
+                if [[ "${args[$k]}" == 'p' || "${args[$k]}" == 'put' ]] ; then
+                    if [ "${args[$m]}" == '' ] ; then
+                        printf "%s\n" "error: missing required argument \`license'"
+                        exit 1
+                    else
+                        filetype=$(printf "%s\n" "${args[$m]}" | awk -F '.' '{ print $2 }')
+                        outputfile="${args[$m]}"
+                        annota block "${filetype}" "$HOME/.config/upnup/headers/${headerfile}" "${outputfile}"
+                        exit 0
+                    fi
+                fi
+            done
+
         elif [[ "${args[$i]}" == 'p' || "${args[$i]}" == 'put' ]] ; then
             if [ "${args[$j]}" == '' ] ; then
                 printf "%s\n" "error: missing required argument \`license'"
                 exit 1
             else
+
                 if [[ ! "${lcs_list[*]}" =~ ${args[$j]} ]] ; then
                     printf "%s\n" "error: ${args[$j]} is not an included \`license"
                     exit 1
