:sparkles: Finished up most functtionality

diff --git a/license b/license
--- a/license
+++ b/license
@@ -1,6 +1,21 @@
 #!/usr/bin/env bash
 set -e
 
+dependencycheck() {
+    numdependencies="$#"
+    dependencies=("$@")
+    missingdependencies=0
+    for ((i = 0; i < numdependencies; i++)) ; do
+        if ! command -v "${dependencies[$i]}" &> /dev/null ; then
+            printf "dependency not met: %s\n" "${dependencies[$i]}"
+            missingdependencies=$((missingdependencies+1))
+        fi
+    done
+    if [ $missingdependencies -gt 0 ]; then
+        exit 1
+    fi
+}
+
 printhelp () {
     printf "%s\n" "Usage: license [options] [command]"
     printf "%s\n" ""
@@ -18,6 +33,8 @@ main () {
     args=("$@")
     user=$USER
     year=$(date | awk -F ' ' '{print $7}')
+    lic_list=( agpl-3.0 apache-2.0 bsd-2-clause bsd-3-clause bsl-1.0 cc0-1.0 cc0-3.0 cc0-4.0 epl-2.0 gpl-2.0 gpl-3.0 lgpl-2.1 mit mpl-2.0 unlicense )
+    mod_list=( agpl-3.0 bsd-2-clause bsd-3-clause mit )
 
     if [[ $# -lt 1 ]] ; then
         printhelp
@@ -33,7 +50,6 @@ main () {
 
         elif [[ "${args[$i]}" == '-u' || "${args[$i]}" == '--user' ]] ; then
             user="${args[$j]}"
-
         elif [[ "${args[$i]}" == '-y' || "${args[$i]}" == '--year' ]] ; then
             year="${args[$j]}"
 
@@ -42,20 +58,27 @@ main () {
                 printf "%s\n" "error: missing required argument \`license'"
                 exit 1
             else
-                cp "$HOME"/.config/license/licenses/"${args[$j]}" ./LICENSE
-                sed "0,/\[year\]/s/\[year\]/$year/" ./LICENSE | sponge ./LICENSE
-                sed "0,/\[fullname\]/s/\[fullname\]/$user/" ./LICENSE | sponge ./LICENSE
+                if [[ ! " ${lic_list[*]} " =~ ${args[$j]} ]]; then
+                    printf "%s\n" "error: ${args[$j]} is not an included \`license"
+                    exit 1
+                fi
+                if [[ " ${mod_list[*]} " =~ ${args[$j]} ]]; then
+                    dependencycheck sponge
+                    cp "$HOME"/.config/license/licenses/"${args[$j]}" ./LICENSE
+                    sed "0,/\[year\]/s/\[year\]/$year/" ./LICENSE | sponge ./LICENSE
+                    sed "0,/\[fullname\]/s/\[fullname\]/$user/" ./LICENSE | sponge ./LICENSE
+                else
+                    cp "$HOME"/.config/license/licenses/"${args[$j]}" ./LICENSE
+                fi
             exit 0
             fi
 
         elif [[ "${args[$i]}" == '-h' || "${args[$i]}" == '--help' ]] ; then
             printhelp
-
         elif [[ "${args[$i]}" == '-V' || "${args[$i]}" == '--version' ]] ; then
             printf "%s\n" "0.0.1" & exit 0
 
         fi
-
     done
 }
 
