:recycle: Added catchall error message

diff --git a/upnup b/upnup
--- a/upnup
+++ b/upnup
@@ -106,6 +106,9 @@ main () {
         elif [[ "${args[$i]}" == '-V' || "${args[$i]}" == '--version' ]] ; then
             printf "%s\n" "0.0.1"
             exit 0
+        else
+            printf "%s\n" "error: unknown argument passed"
+            exit 1
         fi
     done
 }
